// Canonical party data — images from 2082.live (public static assets)
// Party symbol SVGs confirmed at https://2082.live/images/parties/party-XXXX-symbol.svg

export const PARTIES = [
  {
    id: 2,
    name: 'Nepali Congress',
    nameNp: 'नेपाली कांग्रेस',
    abbr: 'NC',
    color: '#0ea5e9',
    bgColor: 'rgba(14,165,233,0.12)',
    logo: 'https://election.onlinekhabar.com/wp-content/uploads/2026/02/Congress.jpg',
    founded: 1947,
    ideology: 'Social Democracy',
    s2079: 57,
    description: 'Centre-left social democratic party. One of Nepal\'s oldest and largest parties.',
  },
  {
    id: 1,
    name: 'Nepal Communist Party (UML)',
    nameNp: 'नेकपा (एमाले)',
    abbr: 'CPN-UML',
    color: '#ef4444',
    bgColor: 'rgba(239,68,68,0.12)',
    logo: 'https://election.onlinekhabar.com/wp-content/uploads/2026/02/UML.jpg',
    founded: 1991,
    ideology: 'Marxism-Leninism',
    s2079: 78,
    description: 'Left-wing communist party led by KP Sharma Oli. Largest party in 2079.',
  },
  {
    id: 41,
    name: 'Rastriya Swatantra Party',
    nameNp: 'राष्ट्रिय स्वतन्त्र पार्टी',
    abbr: 'RSP',
    color: '#2563eb',
    bgColor: 'rgba(37,99,235,0.12)',
    logo: 'https://election.onlinekhabar.com/wp-content/uploads/2022/11/Ghanti.jpg',
    founded: 2022,
    ideology: 'Liberal, Anti-establishment',
    s2079: 20,
    description: 'New liberal party founded in 2022. Popular with Gen Z voters. Led by Rabi Lamichhane.',
  },
  {
    id: 3,
    name: 'CPN (Maoist Centre)',
    nameNp: 'नेकपा (माओवादी केन्द्र)',
    abbr: 'Maoist-C',
    color: '#b91c1c',
    bgColor: 'rgba(185,28,28,0.12)',
    logo: 'https://election.onlinekhabar.com/wp-content/uploads/2026/02/Nepali-Communist-party.jpg',
    founded: 1994,
    ideology: 'Maoism',
    s2079: 18,
    description: 'Former guerrilla movement turned political party, led by Pushpa Kamal Dahal.',
  },
  {
    id: 5,
    name: 'Rastriya Prajatantra Party',
    nameNp: 'राष्ट्रिय प्रजातन्त्र पार्टी',
    abbr: 'RPP',
    color: '#8b5cf6',
    bgColor: 'rgba(139,92,246,0.12)',
    logo: 'https://election.onlinekhabar.com/wp-content/uploads/2026/02/RPP.jpg',
    founded: 1990,
    ideology: 'Hindu nationalism, Conservatism',
    s2079: 14,
    description: 'Right-wing party advocating for Hindu state and constitutional monarchy.',
  },
  {
    id: 4,
    name: 'Janata Samajwadi Party',
    nameNp: 'जनता समाजवादी पार्टी',
    abbr: 'JSP',
    color: '#f59e0b',
    bgColor: 'rgba(245,158,11,0.12)',
    logo: 'https://ui-avatars.com/api/?name=JSP&background=f59e0b&color=fff&size=128',
    founded: 2020,
    ideology: 'Socialism, Madhesi rights',
    s2079: 12,
    description: 'Madhesi-based socialist party representing Terai communities.',
  },
  {
    id: 7,
    name: 'CPN (Unified Socialist)',
    nameNp: 'नेकपा (एकीकृत समाजवादी)',
    abbr: 'CPN-US',
    color: '#f97316',
    bgColor: 'rgba(249,115,22,0.12)',
    logo: 'https://ui-avatars.com/api/?name=US&background=f97316&color=fff&size=128',
    founded: 2021,
    ideology: 'Socialism',
    s2079: 10,
    description: 'Socialist party led by Madhav Kumar Nepal, breakaway from CPN-UML.',
  },
  {
    id: 22,
    name: 'Janamat Party',
    nameNp: 'जनमत पार्टी',
    abbr: 'Janamat',
    color: '#ec4899',
    bgColor: 'rgba(236,72,153,0.12)',
    logo: 'https://ui-avatars.com/api/?name=JAN&background=ec4899&color=fff&size=128',
    founded: 2019,
    ideology: 'Federalism, Madhesi rights',
    s2079: 6,
    description: 'Terai-based federalist party focused on Madhesi rights and identity.',
  },
  {
    id: 32,
    name: 'Nagarik Unmukti Party',
    nameNp: 'नागरिक उन्मुक्ति पार्टी',
    abbr: 'NUP',
    color: '#06b6d4',
    bgColor: 'rgba(6,182,212,0.12)',
    logo: 'https://ui-avatars.com/api/?name=NUP&background=06b6d4&color=fff&size=128',
    founded: 2020,
    ideology: 'Social justice, Tharu rights',
    s2079: 3,
    description: 'Party representing marginalized Tharu and other indigenous communities of Terai.',
  },
  {
    id: 275,
    name: 'Nepali Communist Party (New)',
    nameNp: 'नेपाली कम्युनिस्ट पार्टी',
    abbr: 'NCP',
    color: '#dc2626',
    bgColor: 'rgba(220,38,38,0.12)',
    logo: 'https://ui-avatars.com/api/?name=NCP&background=dc2626&color=fff&size=128',
    founded: 2022,
    ideology: 'Communism',
    s2079: 0,
    description: 'New communist party formed by dissidents. First time contesting in 2082.',
  },
  {
    id: 200,
    name: 'Independent',
    nameNp: 'स्वतन्त्र',
    abbr: 'IND',
    color: '#6b7280',
    bgColor: 'rgba(107,114,128,0.12)',
    logo: 'https://ui-avatars.com/api/?name=IND&background=6b7280&color=fff&size=128',
    founded: null,
    ideology: 'Non-partisan',
    s2079: 7,
    description: 'Candidates not affiliated with any registered political party.',
  },
];

export const PARTY_BY_ID = Object.fromEntries(PARTIES.map(p => [p.id, p]));

// Notable candidates with confirmed image URLs from 2082.live
export const NOTABLE_CANDIDATES = [
  {
    id: 'cand-339653',
    name: 'Balendra Shah',
    nameNp: 'बालेन्द्र शाह',
    aka: 'Balen',
    constituency: 'Jhapa-5',
    constituencyNp: 'झापा-५',
    province: 'Koshi',
    provinceNp: 'कोशी',
    partyId: 41,
    photo: 'https://election.onlinekhabar.com/wp-content/uploads/2026/02/Balen-Shah.jpg',
    notable: 'Current Mayor of Kathmandu, leading the youth-centric RSP movement. Contesting from Jhapa-5 in 2082.',
    notableNp: 'काठमाडौंको वर्तमान मेयर, युवा केन्द्रित RSP आन्दोलनको नेतृत्व गर्दै। २०८२ मा झापा-५ बाट चुनाव लड्दै।',
  },
  {
    id: 'cand-340111',
    name: 'KP Sharma Oli',
    nameNp: 'केपी शर्मा ओली',
    aka: 'KP Oli',
    constituency: 'Jhapa-5',
    constituencyNp: 'झापा-५',
    province: 'Koshi',
    provinceNp: 'कोशी',
    partyId: 1,
    photo: 'https://election.onlinekhabar.com/wp-content/uploads/2026/02/kp-oli-.jpg',
    notable: 'Former Prime Minister and Chairman of CPN-UML.',
    notableNp: 'पूर्व प्रधानमन्त्री र नेकपा (एमाले) का अध्यक्ष।',
  },
  {
    id: 'cand-340888',
    name: 'Ranju Neupane',
    nameNp: 'रञ्जु न्‍यौपाने',
    constituency: 'Kathmandu-1',
    constituencyNp: 'काठमाडौं-१',
    province: 'Bagmati',
    provinceNp: 'बागमती',
    partyId: 41,
    photo: 'https://election.onlinekhabar.com/wp-content/uploads/2026/02/ranju-darsana.jpg',
    notable: 'Prominent youth leader from RSP, leading in Kathmandu-1.',
    notableNp: 'RSP की प्रमुख युवा नेत्री, काठमाडौं-१ मा अग्रणी।',
  },
  {
    id: 'cand-341131',
    name: 'Gajendra Prasad Tumyang Limbu',
    nameNp: 'गजेन्द्र प्रसाद तुम्याङ लिम्बु',
    constituency: 'Taplejung-1',
    constituencyNp: 'ताप्लेजुङ-१',
    province: 'Koshi',
    provinceNp: 'कोशी',
    partyId: 2,
    photo: 'https://ui-avatars.com/api/?name=GL&background=0ea5e9&color=fff&size=200',
    notable: 'Veteran leader from Nepali Congress, contesting in Taplejung.',
    notableNp: 'नेपाली कांग्रेसका पाका नेता, ताप्लेजुङबाट चुनाव लड्दै।',
  },
  {
    id: 'cand-340889',
    name: 'Mohammad Istiyak Rai',
    nameNp: 'मोहम्मद इस्तियाक राई',
    constituency: 'Banke-2',
    constituencyNp: 'बाँके-२',
    province: 'Lumbini',
    provinceNp: 'लुम्बिनी',
    partyId: 1,
    photo: 'https://ui-avatars.com/api/?name=IR&background=ef4444&color=fff&size=200',
    notable: 'Leading candidate from CPN-UML in Banke-2.',
    notableNp: 'बाँके-२ मा नेकपा (एमाले) का अग्रणी उम्मेदवार।',
  },
];
