// Canonical party data — images from 2082.live (public static assets)
// Party symbol SVGs confirmed at https://2082.live/images/parties/party-XXXX-symbol.svg

export const PARTIES = [
  {
    id: 2,
    name: 'Nepali Congress',
    nameNp: 'नेपाली कांग्रेस',
    abbr: 'NC',
    color: '#0ea5e9',
    bgColor: 'rgba(14,165,233,0.12)',
    logo: 'https://2082.live/images/parties/party-3d1d3c87-symbol.svg',
    founded: 1947,
    ideology: 'Social Democracy',
    s2079: 57,
    description: 'Centre-left social democratic party. One of Nepal\'s oldest and largest parties.',
  },
  {
    id: 1,
    name: 'Nepal Communist Party (UML)',
    nameNp: 'नेकपा (एमाले)',
    abbr: 'CPN-UML',
    color: '#ef4444',
    bgColor: 'rgba(239,68,68,0.12)',
    logo: 'https://2082.live/images/parties/party-4c5f9cfa-symbol.svg',
    founded: 1991,
    ideology: 'Marxism-Leninism',
    s2079: 78,
    description: 'Left-wing communist party led by KP Sharma Oli. Largest party in 2079.',
  },
  {
    id: 41,
    name: 'Rastriya Swatantra Party',
    nameNp: 'राष्ट्रिय स्वतन्त्र पार्टी',
    abbr: 'RSP',
    color: '#2563eb',
    bgColor: 'rgba(37,99,235,0.12)',
    logo: 'https://2082.live/images/parties/party-0c9ed580-symbol.svg',
    founded: 2022,
    ideology: 'Liberal, Anti-establishment',
    s2079: 20,
    description: 'New liberal party founded in 2022. Popular with Gen Z voters. Led by Rabi Lamichhane.',
  },
  {
    id: 3,
    name: 'CPN (Maoist Centre)',
    nameNp: 'नेकपा (माओवादी केन्द्र)',
    abbr: 'Maoist-C',
    color: '#b91c1c',
    bgColor: 'rgba(185,28,28,0.12)',
    logo: 'https://2082.live/images/parties/party-2f6c6cab-symbol.svg',
    founded: 1994,
    ideology: 'Maoism',
    s2079: 18,
    description: 'Former guerrilla movement turned political party, led by Pushpa Kamal Dahal.',
  },
  {
    id: 5,
    name: 'Rastriya Prajatantra Party',
    nameNp: 'राष्ट्रिय प्रजातन्त्र पार्टी',
    abbr: 'RPP',
    color: '#8b5cf6',
    bgColor: 'rgba(139,92,246,0.12)',
    logo: 'https://2082.live/images/parties/party-489fbfbc-symbol.svg',
    founded: 1990,
    ideology: 'Hindu nationalism, Conservatism',
    s2079: 14,
    description: 'Right-wing party advocating for Hindu state and constitutional monarchy.',
  },
  {
    id: 4,
    name: 'Janata Samajwadi Party',
    nameNp: 'जनता समाजवादी पार्टी',
    abbr: 'JSP',
    color: '#f59e0b',
    bgColor: 'rgba(245,158,11,0.12)',
    logo: 'https://2082.live/images/parties/party-a1b2c3d4-symbol.svg',
    founded: 2020,
    ideology: 'Socialism, Madhesi rights',
    s2079: 12,
    description: 'Madhesi-based socialist party representing Terai communities.',
  },
  {
    id: 7,
    name: 'CPN (Unified Socialist)',
    nameNp: 'नेकपा (एकीकृत समाजवादी)',
    abbr: 'CPN-US',
    color: '#f97316',
    bgColor: 'rgba(249,115,22,0.12)',
    logo: 'https://2082.live/images/parties/party-c3d4e5f6-symbol.svg',
    founded: 2021,
    ideology: 'Socialism',
    s2079: 10,
    description: 'Socialist party led by Madhav Kumar Nepal, breakaway from CPN-UML.',
  },
  {
    id: 22,
    name: 'Janamat Party',
    nameNp: 'जनमत पार्टी',
    abbr: 'Janamat',
    color: '#ec4899',
    bgColor: 'rgba(236,72,153,0.12)',
    logo: 'https://2082.live/images/parties/party-d4e5f6a7-symbol.svg',
    founded: 2019,
    ideology: 'Federalism, Madhesi rights',
    s2079: 6,
    description: 'Terai-based federalist party focused on Madhesi rights and identity.',
  },
  {
    id: 32,
    name: 'Nagarik Unmukti Party',
    nameNp: 'नागरिक उन्मुक्ति पार्टी',
    abbr: 'NUP',
    color: '#06b6d4',
    bgColor: 'rgba(6,182,212,0.12)',
    logo: 'https://2082.live/images/parties/party-e5f6a7b8-symbol.svg',
    founded: 2020,
    ideology: 'Social justice, Tharu rights',
    s2079: 3,
    description: 'Party representing marginalized Tharu and other indigenous communities of Terai.',
  },
  {
    id: 275,
    name: 'Nepali Communist Party (New)',
    nameNp: 'नेपाली कम्युनिस्ट पार्टी',
    abbr: 'NCP',
    color: '#dc2626',
    bgColor: 'rgba(220,38,38,0.12)',
    logo: 'https://2082.live/images/parties/party-48e58acc-symbol.svg',
    founded: 2022,
    ideology: 'Communism',
    s2079: 0,
    description: 'New communist party formed by dissidents. First time contesting in 2082.',
  },
  {
    id: 200,
    name: 'Independent',
    nameNp: 'स्वतन्त्र',
    abbr: 'IND',
    color: '#6b7280',
    bgColor: 'rgba(107,114,128,0.12)',
    logo: null,
    founded: null,
    ideology: 'Non-partisan',
    s2079: 7,
    description: 'Candidates not affiliated with any registered political party.',
  },
];

export const PARTY_BY_ID = Object.fromEntries(PARTIES.map(p => [p.id, p]));

// Notable candidates with confirmed image URLs from 2082.live
export const NOTABLE_CANDIDATES = [
  {
    id: 'cand-339653',
    name: 'Balendra Shah',
    nameNp: 'बालेन्द्र शाह',
    aka: 'Balen',
    constituency: 'Jhapa-5',
    constituencyNp: 'झापा-५',
    province: 'Koshi',
    partyId: 41,
    photo: 'https://2082.live/images/candidates/339653.jpg',
    notable: '🎤 Former rapper, RSP leader. KEY RACE vs KP Sharma Oli',
    notableNp: '🎤 पूर्व ग्याप्रेमी, RSP नेता। KP शर्मा ओलीसँग मुख्य प्रतिस्पर्धा',
  },
  {
    id: 'cand-340111',
    name: 'KP Sharma Oli',
    nameNp: 'केपी शर्मा ओली',
    aka: 'KP Oli',
    constituency: 'Jhapa-5',
    constituencyNp: 'झापा-५',
    province: 'Koshi',
    partyId: 1,
    photo: 'https://2082.live/images/candidates/340111.jpg',
    notable: '🏛 Former PM, ousted in 2025 Gen Z protests',
    notableNp: '🏛 पूर्व प्रधानमन्त्री, २०२५ जेन जेड आन्दोलनले हटाइए',
  },
  {
    id: 'cand-341131',
    name: 'Gajendra Prasad Tumyang Limbu',
    nameNp: 'गजेन्द्र प्रसाद तुम्याङ लिम्बु',
    constituency: 'Taplejung-1',
    constituencyNp: 'ताप्लेजुङ-१',
    province: 'Koshi',
    partyId: 2,
    photo: 'https://2082.live/images/candidates/341131.jpg',
    notable: '🌿 Koshi Province, Nepali Congress candidate',
    notableNp: '🌿 कोशी प्रदेश, नेपाली कांग्रेस उम्मेदवार',
  },
  {
    id: 'cand-340160',
    name: 'Indra Prasad Thapa',
    nameNp: 'ईन्द्र प्रसाद थापा',
    constituency: 'Taplejung-1',
    constituencyNp: 'ताप्लेजुङ-१',
    province: 'Koshi',
    partyId: 5,
    photo: 'https://2082.live/images/candidates/340160.jpg',
    notable: '🏔 RPP candidate, Taplejung',
    notableNp: '🏔 RPP उम्मेदवार, ताप्लेजुङ',
  },
  {
    id: 'cand-339610',
    name: 'Khel Prasad Budakshetri',
    nameNp: 'खेल प्रसाद बुडाक्षेत्री',
    constituency: 'Taplejung-1',
    constituencyNp: 'ताप्लेजुङ-१',
    province: 'Koshi',
    partyId: 275,
    photo: 'https://2082.live/images/candidates/339610.jpg',
    notable: '🔴 NCP candidate, Taplejung',
    notableNp: '🔴 NCP उम्मेदवार, ताप्लेजुङ',
  },
  {
    id: 'cand-340889',
    name: 'Daka Prasad Gautam',
    nameNp: 'डाक प्रसाद गौतम',
    constituency: 'Ilam-2',
    constituencyNp: 'इलाम-२',
    province: 'Koshi',
    partyId: 200,
    photo: 'https://2082.live/images/candidates/340889.jpg',
    notable: '⚖️ Independent, Ilam-2',
    notableNp: '⚖️ स्वतन्त्र, इलाम-२',
  },
];
